export const CHECKLISTITEMS = [
        {id: "ReviewWeeklySchedule", label: "Review Weekly Schedule"},
        {id: "CheckMailbox", label: "Check Mailbox"},
        {id: "ViewFrontOfTheHouse", label: "View Front Of The House"},
        {id: "TurnOnMainWater", label: "Turn On Main Water"},
        {id: "BugsInsideOutsideFrontDoor", label: "Bugs Inside/Outside Front Door"},
        {id: "Ceilings", label: "Ceilings"},
        {id: "Floors", label: "Floors"},
        {id: "CloseClosets", label: "Close Closets"},
        {id: "TurnToiletsOnOff", label: "Turn Toilets On/Off"},
        {id: "GarageCeiling", label: "Garage Ceiling"},
        {id: "GarageFloor", label: "Garage Floor"},
        {id: "AnyGarageFridge", label: "Any Garage Fridge"}, 
        {id: "AcAirHandlerDrainLine", label: "AC Air Handler Drain Line"},
        {id: "TurnOnOffWaterHeaterInElectricalPanel", label: "Turn On/Off Water Heater In Electrical Panel"},
        {id: "TurnOnOffIceMachine", label: "Turn On/Off Ice Machine"},
        {id: "ThermostatSetTo78ForClose72ForOpening", label: "Thermostat Set To 78 For Close 72 For Opening"},
        {id: "ViewRearOfTheHouse", label: "View Rear Of The House"},
    ];